# Generated by Django 3.2 on 2021-07-03 06:21

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[blog.validators.validate_tags]),
        ),
    ]
